# -*- coding: utf-8 -*-
"""proj02ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lAZo0eGvyvt1qkTPYb8mEvT_HjXmpuI0
"""

#some tests @Marcos Augusto

a = 5
b = 4

#part1
result01 = a == b
print ("São iguais? " + str(result01))

result02 = a != b
print("São diferentes? " + str(result02))

result03 = a > b
print("'a' é maior que 'b'? " + str(result03))
print()

#part2
op01 = 3*a
op02 = 2*b
rcalc01 = op01 > op02
print("'op01' é maior que 'op02'? " + str(rcalc01))

op03 = 4*a
op04 = 5*b
rcalc02 = op03 != op04
print("'op03' é diferente de 'op04'? " + str(rcalc02))
print()

#part3
operation01 = (3*a) + (2*b)
print("Resultado do cáculo 01: " + str(operation01))

operation02 = b*b
print("Resultado do cáculo 02: " + str(operation02))

operation03 = b**2
print("Resultado do cáculo 03: " + str(operation03))

operation04 = a + b
print("Resultado do cáculo 04: " + str(operation04))