# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lAZo0eGvyvt1qkTPYb8mEvT_HjXmpuI0
"""

#some tests

n1 = 3
n2 = 2
n3 = 2.5

result = (2 * n1) * (n2 / 2)
print(result)

result2 = (3 * n1) + n3
print(result2)

result3 = n3* n3 * n3
print(result3)